resources:
  cloud: lambda
  accelerators: GH200:1
  disk_size: 200

envs:
  IMAGE_NAME: null
  HF_TOKEN: null

workdir: .

setup: |
  sudo apt-get update
  sudo apt-get install -y software-properties-common
  sudo add-apt-repository -y ppa:apptainer/ppa
  sudo apt-get update
  sudo apt-get install -y apptainer
  pip install --upgrade huggingface_hub

run: |
  set -e
  export PATH=$HOME/.local/bin:$PATH
  sudo apptainer --verbose build \
    --mksquashfs-args="-comp zstd -Xcompression-level 3" \
    eval_env-${IMAGE_NAME}.sif containers/${IMAGE_NAME}.def
  hf auth login --token "$HF_TOKEN"
  hf upload \
    openeurollm/evaluation_singularity_images \
    eval_env-${IMAGE_NAME}.sif \
    eval_env-${IMAGE_NAME}.sif \
    --repo-type dataset \
    --commit-message "[chore] update ${IMAGE_NAME} image"
