resources:
  cloud: lambda
  cpus: 8+
  disk_size: 200
  accelerators: A10:1

envs:
  IMAGE_NAME: null
  ARCH: ""
  HF_TOKEN: null

workdir: .

setup: |
  sudo apt-get update
  sudo apt-get install -y software-properties-common
  sudo add-apt-repository -y ppa:apptainer/ppa
  sudo apt-get update
  sudo apt-get install -y apptainer
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="$HOME/.local/bin:$PATH"
  uv tool install huggingface_hub[cli]
  if [ -n "$ARCH" ]; then
    sudo apt-get install -y qemu-user-static
  fi

run: |
  set -e
  export PATH="$HOME/.local/bin:$PATH"
  ARCH_FLAG=""
  if [ -n "$ARCH" ]; then ARCH_FLAG="--arch $ARCH"; fi
  sudo apptainer --verbose build $ARCH_FLAG \
    --mksquashfs-args="-comp zstd -Xcompression-level 3" \
    eval_env-${IMAGE_NAME}.sif containers/${IMAGE_NAME}.def
  hf auth login --token "$HF_TOKEN"
  hf upload \
    openeurollm/evaluation_singularity_images \
    eval_env-${IMAGE_NAME}.sif \
    eval_env-${IMAGE_NAME}.sif \
    --repo-type dataset \
    --commit-message "[chore] update ${IMAGE_NAME} image"
